### ISSUE TITLE
Wavenet pre-trained model load error.

### ISSUE THREAD

**Issue by Hunkshang** [JasonWei512/Tacotron-2-Chinese#18]
@JasonWei512 能否帮忙看下，下面load wavenet model 时候出了错误，这会是什么原因造成的？多谢！

Loading checkpoint: logs-Tacotron-2\wave_pretrained/wavenet_model.ckpt-1614000
  0%|          | 0/1 [00:00<?, ?it/s]Starting synthesis! (this will take a while..)

Traceback (most recent call last):
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,1] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: WaveNet_model/inference/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=[?,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"](WaveNet_model/inference/TensorArray, WaveNet_model/inference/TensorArrayStack/range, WaveNet_model/inference/while/Exit_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 100, in <module>
    main()
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 42, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesize.py", line 78, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesize.py", line 55, in run_synthesis
    audio_files = synth.synthesize(mel_spectros, speaker_id_batch, basenames, wav_dir, log_dir)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesizer.py", line 97, in synthesize
    generated_wavs, upsampled_features = self.session.run([self.model.tower_y_hat, self.model.tower_synth_upsampled_local_features], feed_dict=feed_dict)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,1] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: WaveNet_model/inference/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=[?,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"](WaveNet_model/inference/TensorArray, WaveNet_model/inference/TensorArrayStack/range, WaveNet_model/inference/while/Exit_1)]]

Caused by op 'WaveNet_model/inference/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 100, in <module>
    main()
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 94, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "C:/Hunk/Projects/Tacotron/Tacotron-2-Chinese-mandarin-biaobei/synthesize.py", line 42, in synthesize
    wavenet_synthesize(args, hparams, wave_checkpoint)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesize.py", line 78, in wavenet_synthesize
    run_synthesis(args, checkpoint_path, output_dir, hparams)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesize.py", line 19, in run_synthesis
    synth.load(checkpoint_path, hparams)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\synthesizer.py", line 30, in load
    input_lengths=self.input_lengths, synthesis_length=self.synthesis_length, test_inputs=self.targets)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\models\wavenet.py", line 448, in initialize
    softmax=False, quantize=True, log_scale_min=hparams.log_scale_min, log_scale_min_gauss=hparams.log_scale_min_gauss)
  File "C:\Hunk\Projects\Tacotron\Tacotron-2-Chinese-mandarin-biaobei\wavenet_vocoder\models\wavenet.py", line 899, in incremental
    outputs = outputs_ta.stack()
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 856, in stack
    return self._implementation.stack(name=name)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 289, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 303, in gather
    element_shape=element_shape)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 6017, in tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,1] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: WaveNet_model/inference/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[dtype=DT_FLOAT, element_shape=[?,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"](WaveNet_model/inference/TensorArray, WaveNet_model/inference/TensorArrayStack/range, WaveNet_model/inference/while/Exit_1)]]

Process finished with exit code 1

**Comment by JasonWei512** [comment]
没有遇到过 @joyfish
