### ISSUE TITLE
WaveNet训练问题

### ISSUE THREAD

**Issue by zhuyu1326** [JasonWei512/Tacotron-2-Chinese#20]
当我进行waveNet训练时，进行到67456step时出现以下问题：
Step   67456 [1.078 sec/step, loss=6.73029, avg_loss=6.65925]
Generated 64 train batches of size 4 in 0.298 sec
Loss exploded to 378655.87500 at step 674647500, avg_loss=3793.17030]
Exiting due to exception: Loss exploded
Traceback (most recent call last):
  File "/root/Tacotron-2-Chinese/wavenet_vocoder/train.py", line 313, in train
    raise Exception('Loss exploded')
Exception: Loss exploded
2020-04-05 17:29:39.968964: W tensorflow/core/kernels/queue_base.cc:277] _1_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
2020-04-05 17:29:39.969109: W tensorflow/core/kernels/queue_base.cc:277] _0_datafeeder/eval_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main()
  File "train.py", line 132, in main
    train(args, log_dir, hparams)
  File "train.py", line 85, in train
    raise ('Error occured while training Wavenet, Exiting!')
TypeError: exceptions must derive from BaseException
这个情况出现了两次，请问我该如何解决？显卡情况为：RTX 2080 *2

**Comment by JasonWei512** [comment]
去 https://github.com/Rayhane-mamah/Tacotron-2/issues 找找
另外不建议用 Rayhane Mamah 的 WaveNet 实现，https://github.com/r9y9/wavenet_vocoder 效果比较好

**Comment by zhuyu1326** [comment]
谢谢您了，感谢回复




| |
朱禹
|
|
邮箱：zhuyu1326@126.com
|
在2020年04月19日 09:24，魏杰 写道：

去 https://github.com/Rayhane-mamah/Tacotron-2/issues 找找
另外不建议用 Rayhane Mamah 的 WaveNet 实现，https://github.com/r9y9/wavenet_vocoder 效果比较好
