### ISSUE TITLE
关于语音合成

### ISSUE THREAD

**Issue by WYan123** [JasonWei512/Tacotron-2-Chinese#5]
总是出现ValueError: operands could not be broadcast together with shapes (1,1025) (0,) ？
您能帮我解决么

**Comment by JasonWei512** [comment]
https://github.com/Rayhane-mamah/Tacotron-2/issues/321
https://github.com/Rayhane-mamah/Tacotron-2/issues/427

**Comment by WYan123** [comment]
oh my gold ，真是特别感谢。如果每天能给star，我天天给你star，嘿嘿。如有问题，劳烦与你请教，最近在跑Rayhane的程序

**Comment by WYan123** [comment]
当我训练每一步，出现下面情形
Tacotron-2-master apple$ python train.py --model='Tacotron-2'
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    import infolog
  File "/Users/apple/Desktop/Tacotron-2-master/infolog.py", line 26
    print(msg, end=end)
                  ^
SyntaxError: invalid syntax

**Comment by JasonWei512** [comment]
额，你用的不是python 2吧

**Comment by WYan123** [comment]
python3命令就可以了，但是现在在windows上可以预处理，难道要一直用python2？我用的3.6

**Comment by JasonWei512** [comment]
都用python3

**Comment by WYan123** [comment]
thanks，不过lws在windows不太好装，可以加您联系方式么，嘿嘿

**Comment by JasonWei512** [comment]
Lws 应该不是必须的，把关于 lws 的代码全删了应该也能用

Windows 用 pip 装 lws 前也许得先装编译工具：
https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29

**Comment by WYan123** [comment]
谢谢，我都试试，我在Mac上直接可以训练了，只是在windows上试试。非常感谢您的回答

**Comment by WYan123** [comment]
请问您这边运行是在Linux上，按照requirement的大致要求么？在windows有点麻烦啊

**Comment by JasonWei512** [comment]
Ubuntu 和 Windows 10 
Windows 应该装了编译工具后直接 `pip install -r requirements.txt` 就行了

**Comment by WYan123** [comment]
windows下载了visual Studio2015 ，但是pip  install lws 还是不成功。。。。

**Comment by WYan123** [comment]
训练Tacotron-2错误
raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

Step     250 [59.178 sec/step, loss=2.12340, avg_loss=2.40199]
Writing summary at step 250

**Comment by JasonWei512** [comment]
> windows下载了visual Studio2015 ，但是pip  install lws 还是不成功。。。。

报什么错

**Comment by WYan123** [comment]
Installing collected packages: lws
    Running setup.py install for lws ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\panda\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\panda\\AppData\\Local\\Temp\\pip-install-h787x2ev\\lws\\setup.py'"'"'; __file__='"'"'C:\\Users\\panda\\AppData\\Local\\Temp\\pip-install-h787x2ev\\lws\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\panda\AppData\Local\Temp\pip-record-gn5em398\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\panda\AppData\Local\Temp\pip-install-h787x2ev\lws\
    Complete output (13 lines):
    running install
    running build
    running build_ext
    building 'lws' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\lwslib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ilwslib/ -Ic:\users\panda\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include -Ic:\users\panda\appdata\local\programs\python\python36\include -Ic:\users\panda\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tplws.bycython.cpp /Fobuild\temp.win-amd64-3.6\Release\lws.bycython.obj -O3
    cl: 命令行 warning D9002 :忽略未知选项“-O3”
    lws.bycython.cpp
    lws.bycython.cpp(4): fatal error C1083: 无法打开包括文件: “Python.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\panda\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\panda\\AppData\\Local\\Temp\\pip-install-h787x2ev\\lws\\setup.py'"'"'; __file__='"'"'C:\\Users\\panda\\AppData\\Local\\Temp\\pip-install-h787x2ev\\lws\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\panda\AppData\Local\Temp\pip-record-gn5em398\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by WYan123** [comment]
现在真是，Windows装lws ,      linux 装pyaudio困难

**Comment by JasonWei512** [comment]
感觉得装 Windows 10 SDK

**Comment by JasonWei512** [comment]
我是 Python 3.6 + Visual Studio 2019 Community
![image](https://user-images.githubusercontent.com/16899918/71981359-39b91680-325d-11ea-9901-b163eb4febca.png)
![image](https://user-images.githubusercontent.com/16899918/71981378-42a9e800-325d-11ea-93aa-8f8312b8d58e.png)

**Comment by WYan123** [comment]
我试试呢，能否加你微信19821269989 哈哈

**Comment by WYan123** [comment]
Rayhane-mamah的项目tacotron-2的训练步数是100000steps吧？那么如果调整20000步行么？这边感觉跑的挺慢，训练完直接训练wavenet还是tacotron?谢谢解答

**Comment by JasonWei512** [comment]
两万步不够的，我记得应该六到八万步后效果会比较好。
如果你要训练 WaveNet 的话不要用 Rayhane-mamah 写的，我训练出来的效果不太好，[像这个压缩包里W开头的文件那样](https://github.com/JasonWei512/Tacotron-2-Chinese/files/4006791/Griffin-Lim.vs.WaveNet.zip)。用 [r9y9的实现](https://github.com/r9y9/wavenet_vocoder) 比较好，效果类似[这样](https://github.com/JasonWei512/Tacotron-2-Chinese/issues/7)。

**Comment by WYan123** [comment]
那您有组合的语音合成凯源代码么，我看您这是Tacotron-2-Chinese.

**Comment by JasonWei512** [comment]
写个 Bash 或者 PowerShell 脚本，把 Rayhane-mamah/Tacotron-2 和 r9y9/wavenet_vocoder 粘起来…
